name: fitted_gridview
description: A FittedGridView is a package that can fit its content in the parent and show it as gridview.
version: 0.0.1
homepage: https://github.com/ibrahimEltayfe/fitted_gridview

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0